services:
  - type: web
    name: dashboard-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://dashboard-frontend-bdyj.onrender.com
      - key: DATABASE_PATH
        value: /app/db.json

  - type: web
    name: dashboard-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: BACKEND_URL
        value: https://dashboard-backend-jkws.onrender.com